import React from "react";
import { Badge } from "@/ui/Badge";
import { createMetadata } from "@/lib/metadata";

export const metadata = createMetadata({
  title: "Privacy Policy | Medsky HMS",
  description: "Medsky HMS healthcare data privacy policy and data governance practices.",
  path: "/privacy-policy",
});

export default function PrivacyPolicyPage() {
  return (
    <div className="py-12 sm:py-20 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
      <Badge variant="teal" size="md">
        Legal & Compliance
      </Badge>
      <h1 className="text-3xl sm:text-4xl font-black text-slate-900 dark:text-white">
        Privacy Policy
      </h1>
      <p className="text-xs text-slate-400">Last updated: January 2026</p>

      <div className="space-y-6 text-sm sm:text-base text-slate-600 dark:text-slate-300 leading-relaxed">
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">1. Introduction</h2>
          <p>
            Medsky Healthcare Technologies (&ldquo;Medsky&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) is committed to safeguarding the privacy and confidentiality of healthcare organizations, medical practitioners, and patient health data managed through the Medsky Hospital Management Software.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">2. Health Data Protection & Ownership</h2>
          <p>
            All electronic medical records, patient demographic histories, prescription data, and diagnostic investigation values uploaded or generated by client hospitals remain the exclusive intellectual and confidential property of the respective healthcare institution. Medsky acts solely as a secure data processor under standard healthcare confidentiality mandates.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">3. Security Safeguards</h2>
          <p>
            We implement industry-standard technical and organizational security controls, including TLS 1.3 transit encryption, AES-256 resting data encryption, role-based access restrictions, and immutable audit logs.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-slate-900 dark:text-white">4. Contact Privacy Officer</h2>
          <p>
            For privacy inquiries or compliance data auditing requests, please contact our data governance team at <a href="mailto:privacy@medskyhms.com" className="text-teal-600 dark:text-teal-400 font-semibold underline">privacy@medskyhms.com</a>.
          </p>
        </section>
      </div>
    </div>
  );
}
